-- SQLite: integrity constraints, source tables and a normalized fact table.
CREATE TABLE nhanes_demo (
 SEQN INTEGER PRIMARY KEY, RIDAGEYR INTEGER, RIAGENDR INTEGER,
 WTMEC2YR REAL, SDMVSTRA INTEGER, SDMVPSU INTEGER
);
CREATE TABLE nhanes_bio (
 SEQN INTEGER PRIMARY KEY REFERENCES nhanes_demo(SEQN),
 LBXSATSI REAL, LBXSASSI REAL, LBXSGTSI REAL, LBXSAL REAL,
 LBXSCR REAL, LBXSBU REAL,
 LBDSATLC INTEGER CHECK(LBDSATLC IN (0,1)),
 LBDSGTLC INTEGER CHECK(LBDSGTLC IN (0,1))
);
CREATE TABLE lab_measurements (
 SEQN INTEGER NOT NULL REFERENCES nhanes_bio(SEQN),
 RIDAGEYR INTEGER, RIAGENDR INTEGER, SexLabel TEXT, AgeBand TEXT,
 Biomarker TEXT NOT NULL, SourceVariable TEXT, Value REAL, Unit TEXT,
 DetectionFlag INTEGER CHECK(DetectionFlag IN (0,1)),
 IsMissing INTEGER NOT NULL CHECK(IsMissing IN (0,1)),
 IQRReviewFlag INTEGER CHECK(IQRReviewFlag IN (0,1)),
 WTMEC2YR REAL, SDMVSTRA INTEGER, SDMVPSU INTEGER,
 PRIMARY KEY(SEQN,Biomarker),
 CHECK((Value IS NULL AND IsMissing=1) OR (Value IS NOT NULL AND IsMissing=0))
);
CREATE INDEX idx_measurement_group ON lab_measurements(Biomarker,SexLabel,AgeBand);
